kind: pipeline
type: docker
name: plugintest

steps:
- name: test vpc deployment
  image: jmccann/drone-terraform
  tf_version: 0.13.5
  environment:
    IBMCLOUD_API_KEY:
      from_secret: IBMCLOUD_API_KEY
    TF_VAR_region: "us-south"
    TF_VAR_resource_group: "CDE"
    TF_VAR_name: "${DRONE_BUILD_NUMBER}-test-vpc"
  actions:
    - fmt
    - init
    - validate
    - plan
    - apply
trigger:
  branch:
  - drone-testing
